language: node_js
node_js:
  - '8'
before_script: npm run webpack:dev && npm run webpack:prod
cache:
  directories:
  - node_modules
script:
  - npm run test-ci
deploy:
  provider: npm
  email: max.mykhailenko@gmail.com
  api_key:
    secure: EvgG8S1uObLIjOeqQxTPaz4B7JjOApXuXT0OPxJOLfdPcuO67RgneugGIhODr27c96VXvygA8vpNK5db6Ko847MvllHLDNHuzGvod2hOe8GzkhDO06PMf1bqrstvgodHFxSFWU+divY1UQDZh2gMI9s/k3tLOiiAthpGpMnKGlofC8ux7uqNZhK4laggKrD7NnoRBhtMTbDc7Pzdx0qZNfTQPPQYbdRzBlSVvN3gQ3zvN7H/mcXs+AntpNXkPdeMzYMUNaBYBhhBtLJhOKNizrlSbmMRxyZpFl2EKt485dgJqTad323/qvvxe1wp+5J5ilnDxCn1g6cY6oLElxDeHNRVHh5Fiu31DQUxNRojMbbeAtLt1L+Jg4cXJzEldqM9jKHuqyX8G9x+MKu58F4poKGkNrRslzIPn8XePzPeKL2wv/zAH/pHRvd4SZGAnepB/NiNaK4qpIUJey5X8rlPPn9T0BM0ye3JLcnNPNyWYIGcTur28KNJbZdVFSUjAjPpH0bDl/Qz9Q9BJ9VKW9d+2F0ktFqmIEiaU8CqJtN7enWj+89qdDN6dKPoOgJOM6Z2oTAPErAFmeidVi4i7ng4d3eAF4Nz6CKLZN7frO11DGmg/mp1SCZU7RvF8UldRvOdxdEhfqxzz5Ufg3joRC+KX4Wtjn/m6yZLsJO38wzuT88=
  on:
    tags: true
    repo: memCrab/react-pure-modal
    branch: master
