name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply automatic changes
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: src/*.js dist/*.js dist/*.css example/* index.html
          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot
          commit_user_email: max-github-actions-bot@memcrab.com
          commit_author: Author <actions@github.com>

          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: true
